"""rmv campo email extra e add cpf

Revision ID: a056d4663f78
Revises: b448731a51bc
Create Date: 2025-06-09 00:33:15.239158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a056d4663f78'
down_revision: Union[str, None] = 'b448731a51bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autor', sa.Column('cpf', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('autor', 'cpf')
    # ### end Alembic commands ###
